### ISSUE TITLE
Multiple errors on compile

### ISSUE THREAD

**Issue by team2e16** [maidsafe/safe_ffi#8]
As follows:
(On debian jessie)

Compiling safe_ffi v0.0.1 (file:///home/patrick/safe/safe_ffi)
src/implementation.rs:48:29: 50:47 error: this function takes 1 parameter but 3 parameters were supplied [E0061]
src/implementation.rs:48             try!(dir_helper.get((&(dir_key_and_access.0).0, (dir_key_and_access.0).1),
src/implementation.rs:49                                 dir_key_and_access.1,
src/implementation.rs:50                                 &access_level))
<std macros>:1:1: 6:48 note: in expansion of try!
src/implementation.rs:48:13: 50:48 note: expansion site
src/implementation.rs:48:29: 50:47 help: run `rustc --explain E0061` to see a detailed explanation
src/implementation.rs:57:47: 59:102 error: this function takes 1 parameter but 3 parameters were supplied [E0061]
src/implementation.rs:57         current_dir_listing = try!(dir_helper.get(current_dir_info.get_key(),
src/implementation.rs:58                                                   current_dir_info.get_metadata().is_versioned(),
src/implementation.rs:59                                                   current_dir_info.get_metadata().get_access_level()));
<std macros>:1:1: 6:48 note: in expansion of try!
src/implementation.rs:57:31: 59:103 note: expansion site
note: in expansion of for loop expansion
src/implementation.rs:55:5: 60:6 note: expansion site
src/implementation.rs:57:47: 59:102 help: run `rustc --explain E0061` to see a detailed explanation
src/implementation.rs:58:68: 58:82 error: no method named `get_metadata` found for type `safe_nfs::metadata::directory_metadata::DirectoryMetadata` in the current scope
src/implementation.rs:58                                                   current_dir_info.get_metadata().is_versioned(),
                                                                                            ^~~~~~~~~~~~~~
<std macros>:1:1: 6:48 note: in expansion of try!
src/implementation.rs:57:31: 59:103 note: expansion site
note: in expansion of for loop expansion
src/implementation.rs:55:5: 60:6 note: expansion site
src/implementation.rs:59:68: 59:82 error: no method named `get_metadata` found for type `safe_nfs::metadata::directory_metadata::DirectoryMetadata` in the current scope
src/implementation.rs:59                                                   current_dir_info.get_metadata().get_access_level()));
                                                                                            ^~~~~~~~~~~~~~
<std macros>:1:1: 6:48 note: in expansion of try!
src/implementation.rs:57:31: 59:103 note: expansion site
note: in expansion of for loop expansion
src/implementation.rs:55:5: 60:6 note: expansion site
src/lib.rs:229:57: 229:67 error: no method named `get_info` found for type `safe_nfs::directory_listing::DirectoryListing` in the current scope
src/lib.rs:229     let service_home_dir_key = service_home_dir_listing.get_info().get_key();
                                                                       ^~~~~~~~~~
src/lib.rs:242:89: 242:111 error: the type of this value must be known in this context
src/lib.rs:242                                                                   &vec![(service_name, (service_home_dir_key.0.clone(), service_home_dir_key.1))],
                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~
<std macros>:1:1: 4:58 note: in expansion of vec!
src/lib.rs:242:68: 242:146 note: expansion site
src/macros.rs:37:1: 48:2 note: in expansion of ffi_try!
src/lib.rs:239:30: 245:73 note: expansion site
src/lib.rs:263:57: 263:67 error: no method named `get_info` found for type `safe_nfs::directory_listing::DirectoryListing` in the current scope
src/lib.rs:263     let service_home_dir_key = service_home_dir_listing.get_info().get_key();
                                                                       ^~~~~~~~~~
src/lib.rs:272:82: 272:104 error: the type of this value must be known in this context
src/lib.rs:272                                                                  (service_name, (service_home_dir_key.0.clone(), service_home_dir_key.1)),
                                                                                                ^~~~~~~~~~~~~~~~~~~~~~
src/macros.rs:37:1: 48:2 note: in expansion of ffi_try!
src/lib.rs:271:30: 274:72 note: expansion site
error: aborting due to 8 previous errors
Could not compile `safe_ffi`.

**Comment by ustulation** [comment]
Of-course .. it was the middle of the sprint. When you see TODO points in README.md like:
`safe_ffi - changes according to other crates and update test cases`
track its progress in JIRA or submit a PR to address it.

**Comment by team2e16** [comment]
In that case, am I correct to assume that the team develops in the main branch, rather than having a separate branch for dev?

And in that case, in order to compile the last-working code, do I need to download, and then roll back the commits on my machine?

**Comment by Viv-Rajkumar** [comment]
Hey @team2e16 think you've hit one of the edge case issues of the lib setup. Regular rust libs we have recommend their usage via the `crates.io` package manager. This meant we could use the main master branch as the tip of tree for development in a sprint. safe_ffi isnt on `crates.io` and thus led to your issue of seeing the only branch on the repo not compiling while active sprint work was ongoing. 

We'll have this addressed asap and probably end up having a dev branch for this repo with master remaining a stable working branch of the project. Sorry for the inconvenience here. Any approach we use, we'll definetly not force users of the repo to manually rollback commits locally to get a working build :)

**Comment by team2e16** [comment]
Ok, thanks for that. I should have checked, too, whether there were other branches :) But a dedicated dev branch will help greatly :)
